### PR TITLE
Feature/165 Dockerize database

### PR DESCRIPTION
**Pull request by mecm1993**
## What's new? ##

- Add database docker scripts
- Add cleanup scripts
- Modify init scripts to handle docker and cleanup scripts
- Update README 
- Add docker database documentation

Closes [#165]

### CODE REVIEW

**Comment by mecm1993** [comment]
@eatskolnikov I would like to know your opinion regarding the documentation if it is enough or not, or if something is missing or need more clarification. Also, I could not test the `.bat` scripts, if you can help me with to test those I would really appreciate it.

**Comment by eatskolnikov** [comment]
Hicimos un refactoring y nos movimos a .net core 3.1. Además que tienes un conflicto en el init.sh.
Hazle un Rebase a branch.

**Comment by mecm1993** [comment]
Listo @eatskolnikov , ademas modifique el archivo `init.bat` con los cambios de `init.sh` sobre la version de .Net

**Comment by robertlluberes** [comment]
The Author of this PR will not work on it, allow me to continue, so, I made #169 based on this one.

image


Closing this PR.

**Pull request closed without merging**
